const routes = {
    LOGIN: '/login',
    REGISTER: '/register',
    CONFIRM_EMAIL: '/confirm-email',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    MANAGE_PROFILE: '/manage-profile',
    MANAGE_CLIENTS: '/manage-clients',
    CREATE_EDIT_CLIENT: '/create-edit-client',
    MANAGE_USERS: '/user-management',
    HOME: '/home',
    JOURNAL: '/activity-journal',
    PROJECTS: '/projects',
    PROJECT_MANAGEMENT: '/project-manage/:projectId',
    PROJECT_VIEW_PAGE:'/assigned-projects/project-view/:projectId',
    CUSTOMER_PORTAL:'/customer-portal',
    GET_PROJECT_MANAGEMENT_ROUTE: (projectId) => `/project-manage/${projectId}`,
    GET_USER_MANAGE_PROJECTS: (userId) => `/user-projects-manage/${userId}`,
    GET_PROJECT_VIEW_PAGE: (projectId) => `/assigned-projects/project-view/${projectId}`,
    USER_MANAGE_PROJECTS: '/user-projects-manage/:userId',
    PROJECTS_BY_CUSTOMER: '/assigned-projects',
    GET_REPORT_LIST_BY_CUSTOMER_BY_PROJECT_ROUTE:(projectId) => `/customer-report-list/${projectId}`,
    REPORT_LIST_BY_CUSTOMER_BY_PROJECT: '/customer-report-list/:projectId',
    REPORT_LIST_BY_CUSTOMER: '/customer-report-list',
    REPORT_ITEM_BY_CUSTOMER: '/customer-report-item/:dispatchRequestWorkOrderId/:reportTypeId',
    DISPATCH_MANAGEMENT: '/dispatch-manage',
    DISPATCHES: '/dispatches',
    WORK_ORDERS: '/work-orders',
    DISPATCH_PROCESS: '/dispatch-process',
    FULL_SCREEN_MAP: '/full-screen-tech-map',
    SITES_MANAGEMENT: '/sites-management',
    REPORTS_TABLE: '/reports/:projectId',
    GET_REPORTS_TABLE_ROUTE: (dispatchRequestWorkOrderId) => `/reports/${dispatchRequestWorkOrderId}`,
    REPORT_FORM: '/report-form/:dispatchRequestWorkOrderId/:reportTypeId',
    GET_REPORT_FORM_ROUTE: (dispatchRequestWorkOrderId, reportTypeId) => `/report-form/${dispatchRequestWorkOrderId}/${reportTypeId}`,
    BREAK_LIST: '/break-list',
    WORK_ORDERS_MANAGEMENT: '/work-orders-management',
    CYLINDERS_REPORT_FORM: '/report-form/concrete-cylinders/:projectId/:dispatchRequestWorkOrderId',
    GET_CYLINDERS_REPORT_FORM_ROUTE: (projectId, dispatchRequestWorkOrderId) => `/report-form/concrete-cylinders/${projectId}/${dispatchRequestWorkOrderId}`,
    BUDGET_SHEET_LIST: '/budget-sheet-list',
    INVOICE_PAGE: '/invoice-page',
    INVOICE_JOURNAL: '/invoice-journal',
    GET_BUDGET_COMPARISON_ROUTE: (projectId) => `/budget-comparison/${projectId}`,
    BUDGET_COMPARISON_ROUTE: '/budget-comparison/:projectId',
    REPORT_LIST: '/report-list',
    REPORT_ITEM: '/report-item/:dispatchRequestWorkOrderId/:reportTypeId',
    GET_REPORT_ITEM_ROUTE: (dispatchRequestWorkOrderId, reportTypeId) => `/report-item/${dispatchRequestWorkOrderId}/${reportTypeId}`,
    GET_CUSTOMER_REPORT_ITEM_ROUTE: (dispatchRequestWorkOrderId, reportTypeId) => `/customer-report-item/${dispatchRequestWorkOrderId}/${reportTypeId}`,
  
    SOIL_REPORT_FORM: '/report-form/soil-mdr/:projectId/:dispatchRequestWorkOrderId',
    GET_SOIL_REPORT_FORM_ROUTE: (projectId, dispatchRequestWorkOrderId) => `/report-form/soil-mdr/${projectId}/${dispatchRequestWorkOrderId}`,
    SOIL_REPORT_FORM_METHOD_B: '/report-form/soil-mdr-method-b/:projectId/:dispatchRequestWorkOrderId',
    GET_SOIL_REPORT_FORM_ROUTE_METHOD_B: (projectId, dispatchRequestWorkOrderId) => `/report-form/soil-mdr-method-b/${projectId}/${dispatchRequestWorkOrderId}`
};

export default routes;